spring.jackson.property-naming-strategy=SNAKE_CASE

spring.datasource.url=jdbc:sqlite:C:/Users/ciuis/Desktop/FACULTATE/ANUL III/SEM I/Mobile/lab-ionic-02/server/database
spring.jpa.database-platform=org.hibernate.community.dialect.SqliteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
